# Generated by Django 4.2.1 on 2023-05-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_decription',
            new_name='movie_description',
        ),
    ]
