# Generated by Django 4.2.1 on 2023-05-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_rename_movie_decription_movie_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_description',
            field=models.TextField(),
        ),
    ]
