# Generated by Django 4.2.1 on 2023-05-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_movie_time_create_movieactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movie',
        ),
    ]
